[ICP-12063] ZLL RGBW Bulb: Fix format of vid in fingerprint
This bug was causing the following exception during deploy:

```
groovy.lang.MissingMethodException: No signature of method:
script_dth_metadata_220861c6_2bd3_4841_9db9_2c6925a26ddc.fingerprint() is
applicable for argument types: (java.util.LinkedHashMap, java.lang.String)
values: [[profileId:C05E, inClusters:0000, 0003, 0004, 0005, 0006, 0008, 0300,
...], ...]
```